language: node_js
node_js:
  - "11"
dist: trusty
sudo: false

branches:
  only:
  - master

install:
  - git clone --depth 1 https://github.com/Jermolene/TiddlyWiki5.git
  - cd TiddlyWiki5
  - npm link
  - cd ..

script:
  - tiddlywiki --verbose --build index

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  local_dir: output
  on:
    branch: master